### ISSUE TITLE
Cannot find `x86_64-unknown-hermit` target

### ISSUE THREAD

**Issue by flavio** [hermitcore/rust-std-hermit#4]
I've downloaded the 1.72 release for x86_64, unpacked the archive and ran the `./install.sh`.
The script executed successfully, but I wasn't able to find the hermit target.

I'm using latest version of `rustup`, this is the output of `rustup check`:

```console
stable-x86_64-unknown-linux-gnu - Up to date : 1.72.0 (5680fa18f 2023-08-23)
rustup - Up to date : 1.26.0
```

None of these commands return a match:

* `rustup component list | grep hermit`
* `rustup target list | grep hermit`

**Comment by mkroening** [comment]
It is not installed in the `stable` channel but in the explicitly named `1.72.0` channel.

It is expected to not show up in rustup, since we don't install using rustup, but directly into the correct rustup directory.

If the issue persists, feel free to reopen. :)

**Comment by flavio** [comment]
I see, now I got it to work. I had to put a `rust-toolchain.toml` file like that into my project:

```toml
[toolchain]
channel = "1.72.0"
```

Do you plan to add a hermit target to rustup? That would be pretty cool!

**Comment by mkroening** [comment]
> I see, now I got it to work. I had to put a `rust-toolchain.toml` file like that into my project:
> 
> ```toml
> [toolchain]
> channel = "1.72.0"
> ```

That's also what we have done in [hermit-os/hermit-rs-template](https://github.com/hermit-os/hermit-rs-template) if you need further reference. :)

> Do you plan to add a hermit target to rustup? That would be pretty cool!

Distributing artifacts with the rustup would require upgrading the Hermit targets from Tier 3 to Tier 2 (see [Tier 2 target policy](https://doc.rust-lang.org/rustc/target-tier-policy.html#tier-2-target-policy)).

By requesting this, you definitely help with the first point:

> - A tier 2 target must have value to people other than its maintainers. (It may still be a niche target, but it must not be exclusively useful for an inherently closed group.)

Apart from that, I am uncertain if we are ready for that yet, since that would somewhat constrain us in making backwards-incompatible changes to the Hermit ABI.
